### ISSUE TITLE
Ajout des paramètres Query string à l'url de download

### ISSUE THREAD

**Issue by jeremykraemer** [reynadan/ffvbtogcal#1]
Bonjour,

Est-ce qu'il serait compliqué de rajouter la possibilité de passer en paramètres "?saison=&codent=&poule=&team=" à l'URL "/calendar/download" afin qu'il retourne directement le fichier .ics ? 

Cela permettrait d'ajouter dans Google Agenda directement l'URL des différentes équipes du club, avec un lien différent du coup.

**Comment by reynadan** [comment]
Hello,

Merci pour ton issue, c'est une bonne idée pour partager directement les liens de téléchargements
Je m'en occupe bientôt

**Comment by jeremykraemer** [comment]
Hello,

Est-ce que tu as eu le temps de regarder ?

**Comment by reynadan** [comment]
Salut, c'est fait tu peux y accéder à partir du lien formé comme ceci 
/quick/download?saison=&saison=&codent=&poule=&team=

- saison : 2 années avec un tiret entre
- team : nom de l'equipe encodée

exemple : 
http://ffvbtogcal.onrender.com/quick/download?saison=2022-2023&codent=LIRA&poule=RFD&team=SL%20MARGES

Tu peux aussi le retrouver à la fin de la procédure de téléchargement du calendrier 

![image](https://github.com/reynadan/ffvbtogcal/assets/9109378/2aed67e5-f16c-4505-86ea-f3dfa1ad0b15)
